/**
 * mpcdi.xml generation for an MPCDI v2.0, profile "2d" archive.
 *
 * Structure follows the VESA MPCDI Standard v2.0 schema. Annotated outline
 * of what the schema requires (and what we emit) for a single flat-media
 * projector region:
 *
 *   <MPCDI version="2.0" profile="2d" level="1" geometry="1" date="...">
 *     version  : standard version string, "2.0"
 *     profile  : "2d" | "3d" | "a3" | "sl" — "2d" = flat media, no frustum
 *                or coordinateFrame elements are required (those belong to
 *                the 3d/a3 profiles).
 *     level    : conformance level; 1 = warp + blend (+ black level).
 *     geometry : 1 indicates per-region geometry files are present.
 *     <display>                       — exactly one
 *       <buffer id Xresolution Yresolution>   — one per output framebuffer
 *         <region id x y xsize ysize Xresolution Yresolution>
 *           x/y/xsize/ysize are FRACTIONAL positions of the region within
 *           the buffer (floats in [0,1]); X/Yresolution are the region's
 *           pixel dimensions. One region = one projector here, filling the
 *           whole buffer.
 *       </buffer>
 *     </display>
 *     <files>
 *       <fileset region="...">        — @region must match a region id
 *         <geometryWarpFile>
 *           <path>warp.pfm</path>     — 3-channel float32 PFM, R=u G=v B=0
 *           <geometricUnit>2d</geometricUnit>
 *               2d profile uses the dimensionless "2d" unit; physical units
 *               (mm/cm/m/in/ft) only apply to 3d-profile world-space data.
 *           <interpolation>linear</interpolation>
 *         </geometryWarpFile>
 *         <alphaMap bitdepth="8">
 *           <path>alpha.png</path>    — grayscale PNG, multiply blend mask
 *           <gammaEmbedded>1.0</gammaEmbedded>
 *               per-edge gamma is already baked into the pixel values, so
 *               consumers must apply the map linearly => 1.0.
 *         </alphaMap>
 *         <betaMap bitdepth="8">
 *           <path>beta.png</path>     — grayscale PNG, additive black-level
 *         </betaMap>
 *       </fileset>
 *     </files>
 *   </MPCDI>
 */

export interface MpcdiXmlOptions {
  name: string;
  regionId: string;
  width: number;
  height: number;
  /** ISO date string; injected so output is deterministic/testable */
  date: string;
  hasAlpha: boolean;
  hasBeta: boolean;
  warpPath: string;
  alphaPath: string;
  betaPath: string;
}

const escapeXml = (s: string) =>
  s.replace(/[<>&'"]/g, (c) =>
    c === '<' ? '&lt;' : c === '>' ? '&gt;' : c === '&' ? '&amp;' : c === "'" ? '&apos;' : '&quot;',
  );

export function buildMpcdiXml(o: MpcdiXmlOptions): string {
  const rid = escapeXml(o.regionId);
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push(`<!-- Generated by FENCEPOST: ${escapeXml(o.name)} -->`);
  lines.push(
    `<MPCDI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ` +
      `xsi:noNamespaceSchemaLocation="mpcdi.xsd" ` +
      `version="2.0" profile="2d" level="1" geometry="1" date="${escapeXml(o.date)}">`,
  );
  lines.push('  <display>');
  lines.push(`    <buffer id="buffer0" Xresolution="${o.width}" Yresolution="${o.height}">`);
  lines.push(
    `      <region id="${rid}" x="0.0" y="0.0" xsize="1.0" ysize="1.0" ` +
      `Xresolution="${o.width}" Yresolution="${o.height}"/>`,
  );
  lines.push('    </buffer>');
  lines.push('  </display>');
  lines.push('  <files>');
  lines.push(`    <fileset region="${rid}">`);
  lines.push('      <geometryWarpFile>');
  lines.push(`        <path>${escapeXml(o.warpPath)}</path>`);
  lines.push('        <geometricUnit>2d</geometricUnit>');
  lines.push('        <interpolation>linear</interpolation>');
  lines.push('      </geometryWarpFile>');
  if (o.hasAlpha) {
    lines.push('      <alphaMap bitdepth="8">');
    lines.push(`        <path>${escapeXml(o.alphaPath)}</path>`);
    lines.push('        <gammaEmbedded>1.0</gammaEmbedded>');
    lines.push('      </alphaMap>');
  }
  if (o.hasBeta) {
    lines.push('      <betaMap bitdepth="8">');
    lines.push(`        <path>${escapeXml(o.betaPath)}</path>`);
    lines.push('      </betaMap>');
  }
  lines.push('    </fileset>');
  lines.push('  </files>');
  lines.push('</MPCDI>');
  return lines.join('\n') + '\n';
}
