/**
 * mpcdi.xml generation for an MPCDI v2.0, profile "2d" archive — now with
 * multi-region (mosaic / multi-projector) support.
 *
 * Structure follows the VESA MPCDI Standard v2.0 schema. Annotated outline
 * of what the schema requires (and what we emit):
 *
 *   <MPCDI version="2.0" profile="2d" level="1" geometry="1" date="...">
 *     profile  : "2d" = flat media; no frustum/coordinateFrame elements
 *                (those belong to the 3d/a3 profiles).
 *     level    : conformance level; 1 = warp + blend (+ black level).
 *     <display>                        — exactly one
 *       <buffer id Xresolution Yresolution>   — the mosaic framebuffer
 *         <region id x y xsize ysize Xresolution Yresolution/>  — one per
 *           projector. x/y/xsize/ysize are FRACTIONAL positions of the
 *           region within the buffer; X/Yresolution are its pixel dims.
 *       </buffer>
 *     </display>
 *     <files>
 *       <fileset region="...">         — one per region, @region matches id
 *         <geometryWarpFile>
 *           <path>warp_<id>.pfm</path> — float32 PFM; R=u G=v are ABSOLUTE
 *             coordinates into the shared content space (that is how
 *             overlapping regions address the same media band).
 *           <geometricUnit>2d</geometricUnit>
 *           <interpolation>linear</interpolation>
 *         </geometryWarpFile>
 *         <alphaMap bitdepth="8">      — grayscale PNG, multiply mask.
 *           <gammaEmbedded>1.0</gammaEmbedded>  per-edge gamma is baked
 *             into the pixel values; consumers apply the map linearly.
 *         </alphaMap>
 *         <betaMap bitdepth="8">       — grayscale PNG, black-level lift.
 *       </fileset>
 *     </files>
 *   </MPCDI>
 */

export interface MpcdiRegionEntry {
  id: string;
  /** fractional placement within the buffer */
  x: number;
  y: number;
  xsize: number;
  ysize: number;
  /** region pixel dimensions */
  resW: number;
  resH: number;
  warpPath: string;
  alphaPath: string | null;
  betaPath: string | null;
}

export interface MpcdiXmlOptions {
  name: string;
  /** buffer (mosaic framebuffer) pixel dimensions */
  width: number;
  height: number;
  /** ISO date string; injected so output is deterministic/testable */
  date: string;
  regions: MpcdiRegionEntry[];
}

const escapeXml = (s: string) =>
  s.replace(/[<>&'"]/g, (c) =>
    c === '<' ? '&lt;' : c === '>' ? '&gt;' : c === '&' ? '&amp;' : c === "'" ? '&apos;' : '&quot;',
  );

const frac = (v: number) => v.toFixed(6).replace(/0+$/, '0');

export function buildMpcdiXml(o: MpcdiXmlOptions): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push(`<!-- Generated by FENCEPOST: ${escapeXml(o.name)} -->`);
  lines.push(
    `<MPCDI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ` +
      `xsi:noNamespaceSchemaLocation="mpcdi.xsd" ` +
      `version="2.0" profile="2d" level="1" geometry="1" date="${escapeXml(o.date)}">`,
  );
  lines.push('  <display>');
  lines.push(`    <buffer id="buffer0" Xresolution="${o.width}" Yresolution="${o.height}">`);
  for (const r of o.regions) {
    lines.push(
      `      <region id="${escapeXml(r.id)}" x="${frac(r.x)}" y="${frac(r.y)}" ` +
        `xsize="${frac(r.xsize)}" ysize="${frac(r.ysize)}" ` +
        `Xresolution="${r.resW}" Yresolution="${r.resH}"/>`,
    );
  }
  lines.push('    </buffer>');
  lines.push('  </display>');
  lines.push('  <files>');
  for (const r of o.regions) {
    lines.push(`    <fileset region="${escapeXml(r.id)}">`);
    lines.push('      <geometryWarpFile>');
    lines.push(`        <path>${escapeXml(r.warpPath)}</path>`);
    lines.push('        <geometricUnit>2d</geometricUnit>');
    lines.push('        <interpolation>linear</interpolation>');
    lines.push('      </geometryWarpFile>');
    if (r.alphaPath) {
      lines.push('      <alphaMap bitdepth="8">');
      lines.push(`        <path>${escapeXml(r.alphaPath)}</path>`);
      lines.push('        <gammaEmbedded>1.0</gammaEmbedded>');
      lines.push('      </alphaMap>');
    }
    if (r.betaPath) {
      lines.push('      <betaMap bitdepth="8">');
      lines.push(`        <path>${escapeXml(r.betaPath)}</path>`);
      lines.push('      </betaMap>');
    }
    lines.push('    </fileset>');
  }
  lines.push('  </files>');
  lines.push('</MPCDI>');
  return lines.join('\n') + '\n';
}

/** filesystem-safe name fragment derived from a region id */
export function safeFileName(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]+/g, '_') || 'region';
}
